baseURL = "https://prooftoys.org"
languageCode = "en-us"
title = "Prooftoys"
theme = "hugo-whisper-theme"

enableInlineShortcodes = true

[sitemap]
  # Give a reasonable default priority to all pages.
  # Normal range is 0.0 - 1.0.
  priority = 0.5

[params]
  # To use local copies of libs, override with
  # local.toml, which avoids CDNs.
  jquery_url = "https://code.jquery.com/jquery-3.6.0.js"
  dexie_url = "/lib/dexie-3.2.4.mjs"
  popper_url = "/popper.min.js"
  tippy_url = "/tippy-bundle.umd.js"
  mainSections = [ "" ]
  # google_analytics_id = "UA-28801147-2"
  # google_analytics_config = "'UA-28801147-2', { 'anonymize_ip': true }"
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  BookMenuBundle = "/menu.md"

  # Key for access to the ipify.org service
  ipify_key = "at_t2suDoahFs0QQbapi2jqpCkQXCgdU"

  # talkyardServerUrl = "https://comments-for-prooftoys-org.talkyard.net"
  # talkyardScriptUrl = "https://c1.ty-cdn.net/-/talkyard-comments.min.js"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [[module.imports]]
    path = "example.com/prooftoys"
    [[module.imports.mounts]]
      source = "js"
      target = "assets/pt/js"
    [[module.imports.mounts]]
      source = "scss"
      target = "assets/scss"
    [[module.imports.mounts]]
      source = "content"
      target = "content"
    [[module.imports.mounts]]
      source = "layouts"
      target = "layouts"
    [[module.imports.mounts]]
      source = "tests"
      target = "static/tests"
    [[module.imports.mounts]]
      source = "static"
      target = "static/pt"
  [[module.imports]]
    path = "example.com/CDN"
    [[module.imports.mounts]]
      source = "static"
      target = "static/lib"
