baseURL = "https://prooftoys.org"
languageCode = "en-us"
title = "Prooftoys"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[params]
  mainSections = [ "" ]
  google_analytics_id = "UA-28801147-2"
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  BookMenuBundle = "/menu.md"

  talkyardServerUrl = "https://comments-for-prooftoys-org.talkyard.net"
  talkyardScriptUrl = "https://c1.ty-cdn.net/-/talkyard-comments.min.js"

  # For future use: (separate script files, not minified, etc.)
  dev_mode = true
  # For future use: (all resources local)
  airplane_mode = false

  [params.homepage_meta_tags]
#    meta_description = "Hugo Whisper is a documentation theme built with Hugo."

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
