baseURL = "/"
languageCode = "en-us"
title = "Prooftoys"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[params]
  mainSections = [ "" ]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_image = '/images/site-image.png'
  BookMenuBundle = "/menu"

  [params.homepage_meta_tags]
#    meta_description = "Hugo Whisper is a documentation theme built with Hugo."

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
