#!/bin/bash
#
# Deploy prooftoys.org to Netlify from the ~/src/publish area.  

PUB=~/src/publish
TREE=~/tmp/prooftoys-site-tree

run() {
  echo '$' $@
  eval "$@"
}

PSITE=~/src/publish/prooftoys-site
PROOFTOYS=~/src/publish/prooftoys

echo ==== DEPLOYING FROM $PSITE ====
echo ==== USING $PROOFTOYS ====
sleep 1

run cd $PROOFTOYS
run git pull

run cd $PSITE
run git pull

echo
echo ==== BUILD SITE ====
run hugo

echo
echo ==== RELEASE ====
run netlify deploy --site prooftoys.netlify.app --dir public "$@"
