#!/bin/bash
#
# Deploy prooftoys.org to Netlify from the ~/src/publish area.  
#
# You can run this with arg -p or --prod to push to production.
# Or use --alias next to publish to
# https://next--prooftoys.netlify.app/

PUB=~/src/publish

run() {
  echo '$' $@
  eval "$@"
}

PSITE=~/src/publish/prooftoys-site
PROOFTOYS=~/src/publish/prooftoys

echo ==== DEPLOYING FROM $PSITE ====
echo ==== USING $PROOFTOYS ====
sleep 1

run cd $PROOFTOYS
run git pull

# Update node_modules to match config files.
npm install

echo
errcount=$(tsc | grep -w error | wc -l)
if [[ $? = 0 || $? = 2 ]]; then
  echo "TSC: $errcount warnings"
 else
  echo "TSC FAILED" >&2
  exit 1
fi
echo

run cd $PSITE
run git pull

echo
echo ==== BUILD SITE ====
run hugo

echo
echo ==== NETLIFY DEPLOY ====
run netlify deploy --site prooftoys.netlify.app --dir public "$@"

if [ -n "$1" ]; then
  echo ==== PUBLISHED ====
fi
