#!/bin/bash
#
# Deploy prooftoys-site from the ~/src/publish area.

PUB=~/src/publish
TREE=~/tmp/prooftoys-site-tree

run() {
  echo '$' $@
  eval "$@"
}

PSITE=~/src/publish/prooftoys-site
PROOFTOYS=~/src/publish/prooftoys

echo ==== USING $PSITE ====
echo ==== USING $PROOFTOYS ====

run cd $PROOFTOYS
run git pull

run cd $PSITE
run git pull

echo ==== BUILD SITE ====
run ./hugo

echo ==== RELEASE ====
run netlify deploy --site prooftoys.netlify.app --dir public -p
