baseURL = "https://prooftoys.org"
languageCode = "en-us"
title = "Prooftoys"
theme = "hugo-whisper-theme"
themesDir = "../hugo-themes"

enableInlineShortcodes = true

[sitemap]
  # Give a reasonable default priority to all pages.
  # Normal range is 0.0 - 1.0.
  priority = 0.5

[params]
  # To use local copies of libs, override with
  # local.toml, which avoids CDNs.
  # SO -- At runtime, jQuery comes from here:
  # Type info for it comes from node_modules/...
  jquery_url = "https://code.jquery.com/jquery-3.6.0.js"
  dexie_url = "/lib/dexie-3.2.4.mjs"
  popper_url = "/popper.min.js"
  tippy_url = "/tippy-bundle.umd.js"
  mainSections = [ "" ]
  # google_analytics_id = "UA-28801147-2"
  # google_analytics_config = "'UA-28801147-2', { 'anonymize_ip': true }"
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  # Do not set up a default page menu for the sidebars.
  # BookMenuBundle = "/menu.md"

  # Key for access to the ipify.org service
  ipify_key = "at_t2suDoahFs0QQbapi2jqpCkQXCgdU"

  # talkyardServerUrl = "https://comments-for-prooftoys-org.talkyard.net"
  # talkyardScriptUrl = "https://c1.ty-cdn.net/-/talkyard-comments.min.js"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  # To interpret all of these, look at go.mod
  # in this folder, which maps alleged mount URLs
  # to locations in the local filesystem.
  [[module.imports]]
    # Alleged URL to mount:
    # Remapped to local file path in go.mod such as
    # ~/src/prooftoys.
    path = "example.com/prooftoys"
    [[module.imports.mounts]]
      # Location of files relative to path above.
      source = "js"
      # Where to mount it within this workspace:
      # TODO: Remove this when superseded by assets/js.
      target = "assets/pt/js"
    [[module.imports.mounts]]
      # Path to mount:
      source = "js"
      # This also makes js/* "resources" available as /js/* here.
      target = "assets/js"
    [[module.imports.mounts]]
      source = "node_modules"
      # This path is convenient.  Could it cause confusion?
      target = "assets"
    [[module.imports.mounts]]
      source = "scss"
      target = "assets/scss"
    [[module.imports.mounts]]
      source = "content"
      target = "content"
    [[module.imports.mounts]]
      source = "layouts"
      target = "layouts"
    [[module.imports.mounts]]
      source = "tests"
      target = "static/tests"
    [[module.imports.mounts]]
      source = "static"
      target = "static/pt"
  [[module.imports]]
    path = "example.com/CDN"
    [[module.imports.mounts]]
      source = "static"
      target = "static/lib"
