[params]
  # Parameters for serving from local files,
  # overriding CDNs listed in config.toml
  jquery_url = "/lib/jquery-3.6.0.js"
  popper_url = "/popper.min.js"
  tippy_url = "/tippy-bundle.umd.js"
