#!/bin/bash
#
# Deploy prooftoys.org to Netlify from ~/src/
#
# You can run this with arg -p or --prod to push to production.
# Or use --alias next to publish to
# https://next--prooftoys.netlify.app/

PUB=~/src

run() {
  echo '$' $@
  eval "$@"
}

PSITE=$PUB/psite
PROOFTOYS=$PUB/prooftoys

echo ==== DEPLOYING TO "next--prooftoys" FROM $PSITE ====
echo ==== USING $PROOFTOYS ====
sleep 1

run cd $PROOFTOYS
# run git pull

# Update node_modules to match config files.
# npm install

echo
errcount=$(tsc | grep -w error | wc -l)
if [[ $? = 0 || $? = 2 ]]; then
  echo "TSC: $errcount warnings"
 else
  echo "TSC FAILED" >&2
  exit 1
fi
echo

run cd $PSITE
# run git pull

echo
echo ==== BUILD SITE ====
if run hugo; then

  echo
  echo ==== NETLIFY DEPLOY ====
  run netlify deploy --site prooftoys.netlify.app --dir public --alias next "$@"

  if [ -n "$1" ]; then
    echo ==== PUBLISHED ====
  fi
 else
  echo !!!! Hugo build failed !!!!
  exit 1
fi
